# open-pull-requests-limit set to 0 to only allow security updates
# https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - "valispace/automations"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    reviewers:
      - "valispace/operations"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pyparsing"
        versions: [">2.x"] # cannot update further without breaking integration with pint
      - dependency-name: "pylint"
        versions: [">2.14.x"] # cannot update further without breaking integration with pylint-django-2.5.3
    open-pull-requests-limit: 0
    reviewers:
      - "valispace/fn"
