name: 'Build docker image'
description: 'Builds a docker image of this application'
inputs:
  docker-image-name:
    description: 'Name for the docker image'
    required: false
    default: '${{ github.repository }}'
  docker-image-tag:
    description: 'Tag for the docker image'
    required: false
    default: 'latest'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  archive-name:
    description: 'Archive name of the docker image (must include `tar.gz` extension)'
    required: false
    default: '${{ github.repository_owner }}-${{ github.repository_id }}-docker.tar.gz'
runs:
  using: composite
  steps:
    - id: build
      run: docker build --tag ${{ inputs.docker-image-name }}:latest --file "${{ inputs.dockerfile }}" .
      shell: bash
    - id: tag
      run: docker tag ${{ inputs.docker-image-name }}:latest ${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }}
      shell: bash
    - id: save
      run: docker save ${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }} | gzip > "${{ inputs.archive-name }}"
      shell: bash
    - id: test
      run: tar --list --ungzip --file "${{ inputs.archive-name }}"
      shell: bash
