name: 'Develop'

concurrency:
  group: 'develop-${{ github.repository_owner }}-${{ github.event.repository.name }}'
  cancel-in-progress: true  # Allow only one concurrent workflow

on:

  push:
    branches: [develop]

  pull_request:
    branches: [staging]
    types: [closed]

jobs:

  # Build and upload artifacts
  build:

    name: 'Build and Upload Artifacts'

    secrets: inherit

    uses: ./.github/workflows/builder.yml
    with:
      branch-name: 'develop'
      update-major-version: false
      update-minor-version: ${{ (github.event_name == 'pull_request') && github.event.pull_request.merged && (github.event.pull_request.head.ref == 'develop') }}  # The current version was promoted to release candidate (staging) 
      update-patch-version: false
      pre-release-type: 'alpha'
