name: 'Release Candidate'

concurrency:
  group: 'staging-${{ github.repository_owner }}-${{ github.event.repository.name }}'
  cancel-in-progress: true  # Allow only one concurrent workflow

on:

  push:
    branches: [staging]
    paths:
      - 'docker/**'
      - 'backend/**'
      - '!backend/docs/**'
      - '!backend/locust/**'
      - '!backend/scripts/**'
      - '!backend/.exclude'
      - '!backend/.gitignore'
      - '!backend/pyproject.toml'
      - '!backend/requirements-*.txt'

jobs:

  # Build and upload artifacts
  build:

    name: 'Build and Upload Artifacts'

    secrets: inherit

    uses: ./.github/workflows/builder.yml
    with:
      branch-name: '${{ github.ref_name }}'
      update-major-version: false
      update-minor-version: false
      update-patch-version: false
      pre-release-type: 'release-candidate'
